/** Extracted unmodified plan records from apcoweb src/content/site.ts,
 * used to keep the standalone plan demo in sync with published pricing. */
export const plans = [
  {
    id: 'free',
    name: 'FREE',
    description: 'Personal introduction',
    price: 0,
    credits: '500',
    users: '1',
    action: 'Start free',
    api: false,
  },
  {
    id: 'plus',
    name: 'PLUS',
    description: 'Research with API access',
    price: 40,
    credits: '25 000',
    users: '1',
    action: 'View Plus',
    api: true,
  },
  {
    id: 'expert',
    name: 'EXPERT',
    description: 'Advanced search & full filters',
    price: 240,
    credits: '250 000',
    users: '1',
    action: 'View Expert',
    api: true,
  },
  {
    id: 'business',
    name: 'BUSINESS',
    description: 'Team access & private scanning',
    price: 720,
    credits: '1 500 000',
    users: '5',
    action: 'View Business',
    api: true,
  },
] as const;
