export const catalog = [
  {id:'flow',name:'Turquoise Flow',group:'Visual engines',tech:'Canvas 2D',source:'src/visuals/flow/TurquoiseFlow.tsx',description:'Fluid, responsive field with native light and dark variants.',code:"import TurquoiseFlow from './visuals/flow/TurquoiseFlow';\n<TurquoiseFlow theme='dark' speed={1} fps={30} />"},
  {id:'dots',name:'Dot Cascade',group:'Visual engines',tech:'Canvas 2D',source:'src/visuals/dots/DotCascade.tsx',description:'Particle matrix with pointer response and configurable fade.',code:"import DotCascade from './visuals/dots/DotCascade';\n<DotCascade direction='top-to-bottom' />"},
  {id:'globe',name:'Signal Globe',group:'Visual engines',tech:'Canvas 2D',source:'src/visuals/globe/SignalGlobe.tsx',description:'Interactive geographic signal visualization, throttled to a frame budget.',code:"import SignalGlobe from './visuals/globe/SignalGlobe';\n<SignalGlobe fps={30} interactive />"},
  {id:'waves',name:'Ice Sphere Waves',group:'Visual engines',tech:'Canvas 2D',source:'src/visuals/waves/IceSphereWaves.tsx',description:'A dimensional wave field with dark and light palette support.',code:"import IceSphereWaves from './visuals/waves/IceSphereWaves';\n<IceSphereWaves theme='light' />"},
  {id:'rosette',name:'Animated Rosette',group:'Visual engines',tech:'SVG / RAF',source:'src/visuals/shapes/AnimatedShape.tsx',description:'A responsive line-geometry motion primitive.',code:"import AnimatedShape from './visuals/shapes/AnimatedShape';\n<AnimatedShape kind='rosette' color='#111' />"},
  {id:'echo',name:'Echo Rings',group:'Visual engines',tech:'SVG / RAF',source:'src/visuals/shapes/AnimatedShape.tsx',description:'Concentric signal rings and subtle pointer parallax.',code:"import AnimatedShape from './visuals/shapes/AnimatedShape';\n<AnimatedShape kind='echo' color='#111' />"},
  {id:'ai-orb',name:'AI Chat Orb',group:'Visual engines',tech:'React / Canvas 2D',source:'src/visuals/uploads/ai-chat/AIChatOrb.jsx',description:'State-driven assistant indicator: idle, thinking and answer.',code:"import AIChatOrb from './visuals/uploads/ai-chat/AIChatOrb';\n<AIChatOrb state='thinking' size={72} />"},
  {id:'orb-cube',name:'OrbCube Loader',group:'Visual engines',tech:'React / Canvas 2D',source:'src/visuals/uploads/orb-cube/OrbCubeLoader.tsx',description:'Fibonacci point sphere-to-cube morph with depth, responsive sizing and frame control.',code:"import OrbCubeLoader from './visuals/uploads/orb-cube/OrbCubeLoader';\n<OrbCubeLoader size={160} fps={30} />"},
  {id:'query',name:'Query Sequence',group:'Product motion',tech:'DOM / GSAP',source:'src/visuals/product/ProductScene.tsx',description:'Automated search query and interaction sequence.',code:"import ProductScene from './visuals/product/ProductScene';\n<ProductScene scene='query' />"},
  {id:'results',name:'Search Results',group:'Product motion',tech:'DOM / GSAP',source:'src/visuals/product/ProductScene.tsx',description:'Result table, filtering and loading demonstration.',code:"import ProductScene from './visuals/product/ProductScene';\n<ProductScene scene='results' />"},
  {id:'host',name:'Host Intelligence',group:'Product motion',tech:'DOM / GSAP',source:'src/visuals/product/ProductScene.tsx',description:'Host evidence, exposure and vulnerability interaction sequence.',code:"import ProductScene from './visuals/product/ProductScene';\n<ProductScene scene='host' />"},
  {id:'evidence',name:'Evidence View',group:'Product motion',tech:'DOM / GSAP',source:'src/visuals/product/ProductScene.tsx',description:'Technical evidence progression from the walkthrough.',code:"import ProductScene from './visuals/product/ProductScene';\n<ProductScene scene='evidence' />"},
  {id:'suggestions',name:'Suggestions',group:'Product motion',tech:'DOM / GSAP',source:'src/visuals/product/ProductScene.tsx',description:'Contextual recommendations with animated transitions.',code:"import ProductScene from './visuals/product/ProductScene';\n<ProductScene scene='suggestions' />"},
  {id:'api',name:'API Developer Demo',group:'Product motion',tech:'DOM / SVG / GSAP',source:'src/visuals/api/ApiScene.tsx',description:'Request flow, parameters, status transitions and JSON response.',code:"import ApiScene from './visuals/api/ApiScene';\n<ApiScene />"},
  {id:'price',name:'Digit Odometer',group:'Interface motion',tech:'React / WAAPI',source:'src/components/ui/AnimatedPrice.tsx',description:'Digit-by-digit price transitions preserving a readable price label.',code:"import { AnimatedPrice } from './components/ui/AnimatedPrice';\n<AnimatedPrice amount={89} />"},
  {id:'button',name:'Double Button',group:'Interface motion',tech:'React / CSS',source:'src/components/ui/DoubleButton.tsx',description:'Two visual button shapes with a single semantic action.',code:"import { DoubleButton } from './components/ui/DoubleButton';\n<DoubleButton variant='primary'>Get started</DoubleButton>"},
  {id:'accordion',name:'Animated Details',group:'Interface motion',tech:'React / WAAPI',source:'src/components/ui/AnimatedDetails.tsx',description:'Native details/summary keyboard behavior with cancellable height transitions.',code:"import { AnimatedDetails } from './components/ui/AnimatedDetails';\n<AnimatedDetails title='How does it work?'>Answer</AnimatedDetails>"},
  {id:'marquee',name:'Partner Marquee',group:'Interface motion',tech:'React / CSS',source:'src/visuals/marquee/PartnerMarquee.tsx',description:'Seamless repeated partner row with visibility and focus pause.',code:"import PartnerMarquee from './visuals/marquee/PartnerMarquee';\n<PartnerMarquee />"},
  {id:'billing',name:'Billing switch',group:'Interface motion',tech:'React / CSS',source:'src/components/ui/BillingSwitch.tsx',description:'The original two-position billing control.',code:"import { BillingSwitch } from './components/ui/BillingSwitch';\n<BillingSwitch value={period} onChange={setPeriod} />"},
  {id:'planbutton',name:'Plan button',group:'Interface motion',tech:'CSS',source:'src/styles/source-components.css',description:'Original pricing CTA.',code:'<button type="button" className="plan-button">Get started</button>'},
  {"id":"plain","name":"Plain Button","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"Original secondary button shell.","code":"import { PlainButton } from './components/system/SitePrimitives';\n<PlainButton>Sign in</PlainButton>"},
  {"id":"iconaction","name":"Icon Button","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"46px icon action with native 16px glyph.","code":"import { IconAction } from './components/system/SitePrimitives';\n<IconAction name='search' label='Search' />"},
  {"id":"searchfield","name":"Search Input","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"The original search form's surface and focus behavior.","code":"import { SearchField } from './components/system/SitePrimitives';\n<SearchField onSearch={handleSearch} />"},
  {"id":"navmenu","name":"Navigation Disclosure","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"Original navigation trigger and disclosure motion.","code":"import { NavDisclosure } from './components/system/SitePrimitives';\n<NavDisclosure label='Explore' />"},
  {"id":"language","name":"Language Control","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"Active English locale, disabled upcoming locale.","code":"import { LanguageButton } from './components/system/SitePrimitives';\n<LanguageButton />"},
  {"id":"tags","name":"Use Case Tags","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"Original audience section tags.","code":"import { UseCaseTags } from './components/system/SitePrimitives';\n<UseCaseTags items={['Exposure', 'Attack surface']} />"},
  {"id":"plancard","name":"Pricing Card","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"Production pricing card structure.","code":"import { PlanCard } from './components/system/SitePrimitives';\n<PlanCard />"},
  {"id":"modal","name":"Modal Dialog","group":"Interface motion","tech":"React / CSS","source":"src/components/system/SitePrimitives.tsx","description":"Native dialog with original source panel treatment.","code":"import { ModalExample } from './components/system/SitePrimitives';\n<ModalExample />"},
] as const;
export type Item = typeof catalog[number];
export type ComponentId = Item['id'];
export type Group = Item['group'];
export const groups = ['All components','Visual engines','Product motion','Interface motion'] as const;
