import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles/instrument-sans.css';
import './styles/ibm-plex-mono.css';
import './styles/tokens.css';
import './styles/theme-page.css';
import './styles/source-components.css';
import './styles/theme-demos.css';
import './styles/trust-marquee.css';
import './styles/micro-motion.css';
import './styles/gallery.css';
import './styles/system-primitives.css';
import './styles/interface-primitives.css';
import './styles/brand-system.css';
import './styles/foundations.css';
import './styles/icons.css';
import './styles/ux-refinements.css';

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
